enum MenuOptions {
    PAPAS_GRANDES,
    PAPAS_MEDIANAS,
    PAPAS_CHICAS,
    HAMBURGUESA,
    REFRESCO_GRANDE,
    REFRESCO_MEDIANO,
    REFRESCO_CHICO,
    NUGGETS,
    COMBO1,
    COMBO2,
    COMBO3,
    COMBO4,
    COMBO5,
    COMBO6
};
